import Link from "next/link";
import Contact from "./components/home/Contact";
import Footer from "./components/home/Footer";
import styles from "./page.module.css";

const services = [["Websites that bring in enquiries", "A clear, credible home for your business—fast on every screen and easy to update.", "01"], ["Apps that keep customers close", "Make booking, ordering, updates, and everyday service feel effortless.", "02"], ["Systems that save your team time", "Replace scattered spreadsheets and repetitive tasks with a simpler way to work.", "03"]];

export default function Home() {
    return <main className={styles.page}>
        <section className={styles.hero}><div className={styles.heroCopy}><p className={styles.eyebrow}><i /> Digital growth for real businesses</p><h1>Make your business <em>easier to choose.</em></h1><p className={styles.lead}>Nexora helps local and growing businesses show up professionally, serve customers better, and spend less time fighting with technology.</p><div className={styles.heroActions}><Link href="#contact" className={styles.primary}>Start a conversation <span>→</span></Link><Link href="/what-we-do" className={styles.textLink}>See what we do <span>↓</span></Link></div><div className={styles.heroNote}><span>Built for business owners</span><span>Clear advice. Practical delivery.</span></div></div><div className={styles.heroImage}><img src="/hero.jpg" alt="Nexora technology and digital solutions" /><div className={styles.floatingCard}><b>More clarity.</b><span>More time for the work you love.</span></div></div></section>
        <section className={styles.intro}><p className={styles.kicker}>What Nexora brings to the table</p><div><h2>Technology should feel like a <em>good business decision.</em></h2><p>We turn a business need into a useful digital experience—without making you learn a new language first.</p></div></section>
        <section className={styles.services}>{services.map(([title, text, number]) => <article className={styles.service} key={number}><span>{number}</span><div className={styles.icon}>✦</div><h3>{title}</h3><p>{text}</p><Link href="/what-we-do">Explore service <b>→</b></Link></article>)}</section>
        <section className={styles.story}><div className={styles.storyPhoto}><img src="/team-work.jpg" alt="Team discussing a project together" /></div><div className={styles.storyCopy}><p className={styles.kicker}>A partner, not a jargon machine</p><h2>We start with your day-to-day, then make it <em>work better.</em></h2><p>Whether you need a stronger first impression, a smoother customer journey, or a system behind the scenes, we keep the process straightforward and focused on what matters.</p><Link href="/who-we-are" className={styles.secondary}>Meet Nexora <span>→</span></Link></div></section>
        <section className={styles.work}><div className={styles.sectionHeading}><div><p className={styles.kicker}>Ideas made real</p><h2>Work with a purpose, not just a pretty screen.</h2></div><Link href="/portfolio" className={styles.textLink}>View our work <span>→</span></Link></div><div className={styles.workGrid}><article className={styles.workLarge}><img src="/health-tech.jpg" alt="Healthcare technology workspace" /><div><p>Digital solutions</p><h3>Better experiences begin with a better plan.</h3></div></article><article className={styles.workSmall}><img src="/for-grocery-shop.jpg" alt="Local grocery shop" /><div><p>Local business</p><h3>Everyday business, made easier.</h3></div></article></div></section>
        <section className={styles.reasons}><p className={styles.kicker}>Why businesses choose Nexora</p><div className={styles.reasonGrid}><div><b>01</b><h3>Business-first thinking</h3><p>We speak in outcomes, not technical acronyms.</p></div><div><b>02</b><h3>One connected team</h3><p>Strategy, design, build, and support work together.</p></div><div><b>03</b><h3>Built to be useful</h3><p>Every decision earns its place in your business.</p></div></div></section><Contact /><Footer />
    </main>;
}
